[project]
name = "ml-equity-backtester"
version = "0.1.0"
description = "A walk-forward backtester for an ML-driven equity momentum strategy."
authors = ["ElPhysico <vkkleinqt@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
python = ">=3.10,<3.13"
numpy = ">=1.24"
pandas = ">=2.0"
scikit-learn = ">=1.3"
matplotlib = ">=3.7"
seaborn = ">=0.12"
alpha_vantage = ">=3.0.0,<4"
python-dotenv = ">=1.0.1,<2"
jupyter = "*"
pyarrow = ">=14.0"
pip = ">=25.2,<26"



[tasks.benchmarks_download]
args = [
    { "arg" = "mode", "default" = "update" },
]
cmd = "python scripts/download_data.py --mode {{ mode }} --tickers CSPX.L IWDA.AS"


[tasks.demo_download]
args = [
    { "arg" = "mode", "default" = "update" },
]
cmd = "python scripts/download_data.py --mode {{ mode }} --universe_file config/universes/2025-10_DEMO15.csv"


[tasks.demo_elasticnet_topn]
cmd = "python scripts/demo15_elasticnet_topn.py"

