[project]
name = "ml-equity-backtester"
version = "0.1.0"
description = "A walk-forward backtester for an ML-driven equity momentum strategy."
authors = ["ElPhysico <vkkleinqt@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
python = ">=3.10,<3.13"
numpy = ">=1.24"
pandas = ">=2.0"
scikit-learn = ">=1.3"
matplotlib = ">=3.7"
seaborn = ">=0.12"
alpha_vantage = ">=3.0.0,<4"
python-dotenv = ">=1.0.1,<2"
jupyter = "*"
pyarrow = ">=14.0"
pip = ">=25.2,<26"

[tasks]
download_init = "python scripts/download_data.py --mode init"
download_update = "python scripts/download_data.py --mode update"

benchmarks = "python scripts/benchmarks.py"
