# Split safe and existing window for these 20 selected stocks
min_date: "2015-08-01"
max_date: "2025-09-30"

benchmarks:
  - CSPX.L
  - IWDA.AS

stocks:
  - ADBE
  - AKAM
  - AMD
  - AR
  - BB
  - BIIB
  - BRK.B
  - CIEN
  - EL
  - INCY
  - MCO
  - MGM
  - NFLX
  - QGEN
  - TMO