simulator_params:
  start: "1990-09-19"                 # simulation start date
  end: "2025-10-10"                   # simulation end date
  seed: 1990                          # RNG seeding

gbm_params:
  n_tickers: 100                      # number gbm tickers to be simulated
  ann_mu: 0.06                        # annualized drift
  ann_sigma: 0.25                     # annualized volatility
  tdy: 252                            # trading days per year for gbm universe

benchmarks:
  # - CSPX.L                            # SP500
  # - IWDA.AS                           # MSCI World
  - BH_EW_self                        # Buy-and-Hold equal weight of universe
  - MR_EW_self                        # Monthly rebalance equal weight universe

save: True                            # toggles saving backtest data to disc
out_dir: "outputs"                    # save dir relative to project root
run_name: "DEMO_synth"

feature_params:
  P: 12                               # momentum lookback months
  skip: 1                             # momentum skip months
  min_obs: 10                         # min observables for monthly volatility
  annualize: False                    # annualize volatility?
  ddof: 0                             # delta degrees of freedom for std

model_params:
  alpha: 0.001                        # regularization strength
  l1_ratio: 0.5                       # L1 - L2 penalty mixing
  random_state: 0                     # no effect with current implementation
  min_train_samples: 100              # skip months with fewer samples

backtest_params:
  rank_col: "y_pred"                  # label column used for ranking top-N
  N: 5                                # top-N tickers to select each month
  cost_bps: 5                         # one-way trading cost in basis points
